[package]
name = "php-sys"
version = "7.2.12"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>", "Heinz Gies <heinz@licenser.net>"]
links = "php7"
build = "build.rs"

[build-dependencies]
cc = "1.0"
num_cpus="1.0"
